name: Update README with Current Date
on:
  push:
    branches:
      - master
jobs:
  update_readme:
    runs-on: ubuntu-latest
    env:
      TODAY_DATE: $(date +"%Y-%m-%d")
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      #- name: Update README
      #  run: |
      #    echo "Updating README..."
      #    sed -i "s/linkjedateupdate/Today\'s date is: $TODAY_DATE/g" README.md
      - name: Check date
        run: 'echo "Current date set as environment variable: ${TODAY_DATE}"'
